# Generated by Django 5.2.1 on 2025-05-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=16)),
                ('amount', models.IntegerField()),
                ('code', models.CharField(max_length=10)),
                ('m_id', models.CharField(max_length=100, unique=True)),
                ('c_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
